name: kindergarten-garden
version: 1.1.1.8

dependencies:
    - base
    - containers
    # - map

library:
    exposed-modules: Garden
    source-dirs: src
    # ghc-options: -Wall
    dependencies:
        - split # List here the packages you
    # - bar       # want to use in your solution.

tests:
    test:
        main: Tests.hs
        source-dirs: test
        dependencies:
            - kindergarten-garden
            - hspec
