name: simple-cipher
version: 1.2.0.5

dependencies:
    - base
    - containers

library:
    exposed-modules: Cipher
    source-dirs: src
    dependencies:
        - random # List here the packages you
    # - bar       # want to use in your solution.

tests:
    test:
        main: Tests.hs
        source-dirs: test
        dependencies:
            - simple-cipher
            - hspec
