name: atbash-cipher
version: 1.2.0.6

dependencies:
    - base
    - containers

library:
    exposed-modules: Atbash
    source-dirs: src
    ghc-options: -Wall
    dependencies:
        - split # List here the packages you
    # - bar       # want to use in your solution.

tests:
    test:
        main: Tests.hs
        source-dirs: test
        dependencies:
            - atbash-cipher
            - hspec
